/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cmsc335_final_project;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.stage.Stage;

public class App extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) throws Exception {
        // Create a new label
        Label label = new Label("Hello, World!");

        // Create a new scene
        Scene scene = new Scene(label);

        // Set the scene of the stage
        stage.setScene(scene);

        // Show the stage
        stage.show();
    }
}
