/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cmsc335_final_project;

import cmsc335_final_project.panels.CarPanel;
import cmsc335_final_project.panels.ControlPanel;
import cmsc335_final_project.panels.TimePanel;
import cmsc335_final_project.panels.TrafficLightPanel;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;

public class App extends Application {
    private static TimePanel timePanel;
    private static TrafficLightPanel trafficLightPanel;
    private static CarPanel carPanel;
    private static ControlPanel controlPanel;

    public static void main(String[] args) {
        timePanel = new TimePanel();
        trafficLightPanel = new TrafficLightPanel();
        carPanel = new CarPanel();
        controlPanel = new ControlPanel();
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        // Create the main layout pane
        BorderPane root = new BorderPane();

        // Initalize the time panel and add it to the top of the main layout
        timePanel.initTimePanel(root);
        trafficLightPanel.initTrafficLightPanel(root);
        carPanel.initCarsPanel(root);
        controlPanel.initControlPanel(root, carPanel, trafficLightPanel);

        // Set the scene with the main layout pane and default dimensions (e.g.,
        // 800x600)
        Scene scene = new Scene(root, 800, 600);

        // Set the stage properties
        primaryStage.setTitle("Traffic Congestion Mitigation Simulation");
        primaryStage.setScene(scene);

        // Show the primary stage/window
        primaryStage.show();

        // Start the time update
        timePanel.startTimeUpdate();
        trafficLightPanel.startTrafficLightCycle();
        carPanel.startCarMovementUpdate();
    }

}
